// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function Decrypt(arg1:string,arg2:string,arg3:string):Promise<handler.CryptoResponse>;

export function Encrypt(arg1:string,arg2:string,arg3:string):Promise<handler.CryptoResponse>;
