// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function GenerateKeyPair(arg1:number,arg2:string,arg3:string):Promise<handler.RSAKeyPair>;
