// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateToTimestamp(arg1:string,arg2:string):Promise<number>;

export function GetCurrentTime(arg1:string):Promise<Record<string, any>>;

export function TimestampToDate(arg1:number,arg2:string):Promise<string>;
