// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DateToTimestamp(arg1, arg2) {
  return window['go']['handler']['TimeHandler']['DateToTimestamp'](arg1, arg2);
}

export function GetCurrentTime(arg1) {
  return window['go']['handler']['TimeHandler']['GetCurrentTime'](arg1);
}

export function TimestampToDate(arg1, arg2) {
  return window['go']['handler']['TimeHandler']['TimestampToDate'](arg1, arg2);
}
