// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function CheckUpdate():Promise<handler.VersionInfo>;

export function Download():Promise<Array<number>>;

export function GetCurrentVersion():Promise<string>;

export function GetVersionLatest():Promise<handler.VersionInfo>;
