// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handler} from '../models';

export function CheckUpdate():Promise<handler.UpdateResult>;

export function GetCurrentVersion():Promise<string>;
