// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['handler']['VersionHandler']['CheckUpdate']();
}

export function Download() {
  return window['go']['handler']['VersionHandler']['Download']();
}

export function GetCurrentVersion() {
  return window['go']['handler']['VersionHandler']['GetCurrentVersion']();
}

export function GetVersionLatest() {
  return window['go']['handler']['VersionHandler']['GetVersionLatest']();
}
