// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternal(arg1:string):Promise<void>;

export function SaveQRCode(arg1:string,arg2:string):Promise<string>;
